# yazi.toml
[mgr]

edit = [
    { run = '${EDITOR:-nvim} "$@"', desc = "$EDITOR", block = true, for = "unix" },
    { run = 'nvim %*', orphan = true, desc = "nvim", for = "windows" },
    { run = 'nvim %*', block = true, desc = "nvim (block)", for = "windows" },
]

[flavor]
use = "dracula"
